<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-47P2MTB" failures="6" tests="29" name="Surefire test" time="56.223" errors="0" timestamp="2024-12-06T10:42:46 IST">
  <testcase classname="api.test.PetTest" name="testAddNewPetPostResponse" time="3.967"/>
  <testcase classname="api.test.PetTest" name="testAddNewPetPostResponse" time="1.31"/>
  <testcase classname="api.test.PetTest" name="testAddNewPetPostResponse" time="1.732"/>
  <testcase classname="api.test.PetTest" name="testUpdateExistingPetPutResponse" time="1.295"/>
  <testcase classname="api.test.PetTest" name="testUpdateExistingPetPutResponse" time="1.373"/>
  <testcase classname="api.test.PetTest" name="testUpdateExistingPetPutResponse" time="1.621"/>
  <testcase classname="api.test.PetTest" name="testFindPetByStatusGetResponse" time="1.358"/>
  <testcase classname="api.test.PetTest" name="testFindPetByPetIDGetResponse" time="2.761"/>
  <testcase classname="api.test.PetTest" name="testFindPetByPetIDGetResponse" time="1.818"/>
  <testcase classname="api.test.PetTest" name="testFindPetByPetIDGetResponse" time="1.388"/>
  <testcase classname="api.test.PetTest" name="testUpdatePetPuTResponse" time="2.94"/>
  <testcase classname="api.test.PetTest" name="testUploadPetImagePostResponse" time="3.026"/>
  <testcase classname="api.test.PetTest" name="testDeletePetDeleteResponse" time="2.962"/>
  <testcase classname="api.test.PetTest" name="deleberatlyFailTest" time="0.001">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at api.test.PetTest.deleberatlyFailTest(PetTest.java:575)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- deleberatlyFailTest -->
  <testcase classname="api.test.PetTest" name="deleberatlySkippedTest1" time="0.0">
    <skipped/>
  </testcase> <!-- deleberatlySkippedTest1 -->
  <testcase classname="api.test.PetTest" name="deleberatlySkippedTest2" time="0.0">
    <skipped/>
  </testcase> <!-- deleberatlySkippedTest2 -->
  <testcase classname="api.test.StoreTest" name="testPostStoreResponse" time="1.355"/>
  <testcase classname="api.test.StoreTest" name="testGetStoreOrderResponse" time="3.42">
    <failure type="java.lang.AssertionError" message="Expected status code is 404 for invalid order ID. expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Expected status code is 404 for invalid order ID. expected [404] but found [200]
at api.test.StoreTest.testGetStoreOrderResponse(StoreTest.java:212)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testGetStoreOrderResponse -->
  <testcase classname="api.test.StoreTest" name="testGetStoreInventoriesResponse" time="1.683">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Response body doesn&amp;apos;t match expectation.
Expected: The content to match the given JSON schema.
error: object instance has properties which are not allowed by the schema: [&amp;quot;05.12.2024&amp;quot;,&amp;quot;Avilable&amp;quot;,&amp;quot;The Best Dog of World&amp;quot;,&amp;quot;not available&amp;quot;,&amp;quot;pending&amp;quot;]
    level: &amp;quot;error&amp;quot;
    schema: {&amp;quot;loadingURI&amp;quot;:&amp;quot;#&amp;quot;,&amp;quot;pointer&amp;quot;:&amp;quot;/definitions/Welcome8&amp;quot;}
    instance: {&amp;quot;pointer&amp;quot;:&amp;quot;&amp;quot;}
    domain: &amp;quot;validation&amp;quot;
    keyword: &amp;quot;additionalProperties&amp;quot;
    unwanted: [&amp;quot;05.12.2024&amp;quot;,&amp;quot;Avilable&amp;quot;,&amp;quot;The Best Dog of World&amp;quot;,&amp;quot;not available&amp;quot;,&amp;quot;pending&amp;quot;]
error: object has missing required properties ([&amp;quot;placed&amp;quot;,&amp;quot;ratvelleg&amp;quot;,&amp;quot;status&amp;quot;])
    level: &amp;quot;error&amp;quot;
    schema: {&amp;quot;loadingURI&amp;quot;:&amp;quot;#&amp;quot;,&amp;quot;pointer&amp;quot;:&amp;quot;/definitions/Welcome8&amp;quot;}
    instance: {&amp;quot;pointer&amp;quot;:&amp;quot;&amp;quot;}
    domain: &amp;quot;validation&amp;quot;
    keyword: &amp;quot;required&amp;quot;
    required: [&amp;quot;available&amp;quot;,&amp;quot;placed&amp;quot;,&amp;quot;ratvelleg&amp;quot;,&amp;quot;sold&amp;quot;,&amp;quot;status&amp;quot;,&amp;quot;string&amp;quot;]
    missing: [&amp;quot;placed&amp;quot;,&amp;quot;ratvelleg&amp;quot;,&amp;quot;status&amp;quot;]

  Actual: {&amp;quot;sold&amp;quot;:18,&amp;quot;The Best Dog of World&amp;quot;:1,&amp;quot;string&amp;quot;:743,&amp;quot;pending&amp;quot;:6,&amp;quot;available&amp;quot;:216,&amp;quot;not available&amp;quot;:1,&amp;quot;Avilable&amp;quot;:1,&amp;quot;05.12.2024&amp;quot;:1}
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Response body doesn't match expectation.
Expected: The content to match the given JSON schema.
error: object instance has properties which are not allowed by the schema: ["05.12.2024","Avilable","The Best Dog of World","not available","pending"]
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Welcome8"}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "additionalProperties"
    unwanted: ["05.12.2024","Avilable","The Best Dog of World","not available","pending"]
error: object has missing required properties (["placed","ratvelleg","status"])
    level: "error"
    schema: {"loadingURI":"#","pointer":"/definitions/Welcome8"}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["available","placed","ratvelleg","sold","status","string"]
    missing: ["placed","ratvelleg","status"]

  Actual: {"sold":18,"The Best Dog of World":1,"string":743,"pending":6,"available":216,"not available":1,"Avilable":1,"05.12.2024":1}

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:107)
at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:238)
at api.test.StoreTest.testGetStoreInventoriesResponse(StoreTest.java:278)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 42 stack frames]]>
    </failure>
  </testcase> <!-- testGetStoreInventoriesResponse -->
  <testcase classname="api.test.StoreTest" name="testDeleteStoreOrderResponse" time="3.019">
    <failure type="java.lang.AssertionError" message="Expected status code is 200. expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Expected status code is 200. expected [200] but found [404]
at api.test.StoreTest.testDeleteStoreOrderResponse(StoreTest.java:365)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteStoreOrderResponse -->
  <testcase classname="api.test.UserTest" name="createUser_shouldReturn200StatusCode" time="1.798"/>
  <testcase classname="api.test.UserTest" name="getUser_shouldRespondWithinExpectedTime" time="1.573">
    <failure type="java.lang.AssertionError" message="Response time is outside the expected range. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Response time is outside the expected range. expected [true] but found [false]
at api.test.UserTest.getUser_shouldRespondWithinExpectedTime(UserTest.java:182)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- getUser_shouldRespondWithinExpectedTime -->
  <testcase classname="api.test.UserTest" name="updateUser_shouldReturn200StatusCode" time="1.594">
    <failure type="org.json.JSONException" message="JSONObject[&amp;quot;id&amp;quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["id"] not found.
at org.json.JSONObject.get(JSONObject.java:596)
at api.test.UserTest.updateUser_shouldReturn200StatusCode(UserTest.java:305)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- updateUser_shouldReturn200StatusCode -->
  <testcase classname="api.test.UserTest" name="updateUser_withInvalidUsername_shouldHandleGracefully" time="1.277"/>
  <testcase classname="api.test.UserTest" name="loginUser_shouldReturn200StatusCode" time="1.417"/>
  <testcase classname="api.test.UserTest" name="logoutUser_shouldReturn200StatusCode" time="1.397"/>
  <testcase classname="api.test.UserTest" name="deleteUser_shouldReturn200StatusCode" time="1.284"/>
  <testcase classname="api.test.UserTest" name="deletedUser_shouldNotBeFetched_shouldReturn404Error" time="1.325"/>
  <testcase classname="api.test.UserTest" name="createUsersInBulk_shouldReturn200StatusCode" time="1.369"/>
</testsuite> <!-- Surefire test -->
